"""Outline the supplied lockups using hash-pinned, OFL-licensed fonts.

This is a maintainer tool, never part of an application build. See
assets/brand/WORDMARK.md. --check is read-only; --download explicitly permits
fetching missing fonts into --font-dir. No system-installed fonts are used.
"""

import argparse
import copy
import hashlib
import importlib.metadata
import json
from pathlib import Path
import urllib.request
import xml.etree.ElementTree as ET

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.basePen import BasePen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.svgLib.path import parse_path
from fontTools.ttLib import TTFont
import uharfbuzz as hb


ROOT = Path(__file__).resolve().parent.parent
BRAND = ROOT / 'assets/brand'
SOURCES = ROOT / 'tool/generate_wordmark_sources'
NS = 'http://www.w3.org/2000/svg'
ET.register_namespace('', NS)
ADOBE_COMMIT = '6c709ca72d3d7c46ab42ebecc1a26e7d69595a37'
GOOGLE_COMMIT = '0b58fb370093f9a9f4ff785d94405710b79de67c'
DEPENDENCIES = {'fonttools': '4.65.0', 'uharfbuzz': '0.56.2'}
FONTS = {
    'han-heavy': {
        'filename': 'SourceHanSansCN-Heavy.otf',
        'family': 'Source Han Sans CN', 'weight': 900, 'version': '2.005',
        'sha256': '88c749b0a54a0800124ded6544e399302ed224aa49992ea364b88769f825c54c',
        'url': f'https://raw.githubusercontent.com/adobe-fonts/source-han-sans/{ADOBE_COMMIT}/SubsetOTF/CN/SourceHanSansCN-Heavy.otf',
        'license': 'LICENSES/SourceHanSans-OFL-1.1.txt',
    },
    'han-regular': {
        'filename': 'SourceHanSansCN-Regular.otf',
        'family': 'Source Han Sans CN', 'weight': 400, 'version': '2.005',
        'sha256': 'e2bc8a2e7f37474b774fff8db758681ece40bb6947a90d571bce9dd60671a8e4',
        'url': f'https://raw.githubusercontent.com/adobe-fonts/source-han-sans/{ADOBE_COMMIT}/SubsetOTF/CN/SourceHanSansCN-Regular.otf',
        'license': 'LICENSES/SourceHanSans-OFL-1.1.txt',
    },
    'inter-medium': {
        'filename': 'InterTight-wght.ttf',
        'family': 'Inter Tight', 'weight': 500, 'version': '3.004',
        'variations': {'wght': 500},
        'sha256': 'b81b73dcb64df3c230cabade7df6c5773bf863233f24c9ee51087519f1f88b6f',
        'url': f'https://raw.githubusercontent.com/google/fonts/{GOOGLE_COMMIT}/ofl/intertight/InterTight%5Bwght%5D.ttf',
        'license': 'LICENSES/InterTight-OFL-1.1.txt',
    },
}
LICENSES = {
    'LICENSES/SourceHanSans-OFL-1.1.txt': {
        'sha256': 'fcac737e761ec63dbfbdce11030a1780161920d80315edba9c8beff1c2bac5a2',
        'url': f'https://raw.githubusercontent.com/adobe-fonts/source-han-sans/{ADOBE_COMMIT}/LICENSE.txt',
    },
    'LICENSES/InterTight-OFL-1.1.txt': {
        'sha256': '50240ab035cf1b6b3307940235481d515c4b6de3ab1fa843dbe59e7892cb9d58',
        'url': f'https://raw.githubusercontent.com/google/fonts/{GOOGLE_COMMIT}/ofl/intertight/OFL.txt',
    },
}


def digest(data):
    return hashlib.sha256(data).hexdigest()


def number(value):
    result = f'{value:.6f}'.rstrip('0').rstrip('.')
    return '0' if result in ('', '-0') else result


def rounded(values):
    return [float(number(value)) for value in values]


class DartPathPen(BasePen):
    def __init__(self):
        super().__init__(None)
        self.commands = []

    def command(self, name, *points):
        values = ', '.join(number(v) for point in points for v in point)
        self.commands.append(f'  ..{name}({values})')

    def _moveTo(self, point):
        self.command('moveTo', point)

    def _lineTo(self, point):
        self.command('lineTo', point)

    def _curveToOne(self, point1, point2, point3):
        self.command('cubicTo', point1, point2, point3)

    def _qCurveToOne(self, point1, point2):
        self.command('quadraticBezierTo', point1, point2)

    def _closePath(self):
        self.commands.append('  ..close()')


def dart_wordmark(path, bounds):
    left, top, right, bottom = bounds
    pen = DartPathPen()
    parse_path(path.attrib['d'], TransformPen(pen, (1, 0, 0, 1, -left, -top)))
    width, height = number(right - left), number(bottom - top)
    code = [
        '// Generated by tool/generate_wordmark.py. Do not edit by hand.',
        '// Source Han Sans CN Heavy 2.005; see assets/brand/WORDMARK.md.',
        "import 'dart:ui';",
        '',
        f'const brandWordmarkSize = Size({width}, {height});',
        f'const brandWordmarkBounds = Rect.fromLTWH(0, 0, {width}, {height});',
        '',
        '/// The supplied Chinese wordmark, normalized to its painted bounds.',
        'Path createBrandWordmarkPath() => Path()',
        *pen.commands,
    ]
    return ('\n'.join(code) + ';\n').encode('utf-8')


def output_path(name):
    return (ROOT / 'lib/ui/field' if name.endswith('.dart') else BRAND) / name


def load_fonts(directory, download):
    fonts = {}
    for key, info in FONTS.items():
        path = directory / info['filename']
        if not path.exists() and download:
            data = urllib.request.urlopen(info['url'], timeout=60).read()
            if digest(data) != info['sha256']:
                raise ValueError(f'Download hash mismatch: {path.name}')
            directory.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
        data = path.read_bytes()
        if digest(data) != info['sha256']:
            raise ValueError(f'Font hash mismatch: {path.name}')
        fonts[key] = (data, TTFont(path))
    return fonts


def outline_text(element, fonts):
    text = element.text
    family = element.attrib['font-family'].split(',')[0]
    weight = int(element.attrib['font-weight'])
    key = next(key for key, info in FONTS.items()
               if info['family'] == family and info['weight'] == weight)
    data, tt = fonts[key]
    face = hb.Face(data)
    font = hb.Font(face)
    font.scale = (face.upem, face.upem)
    variations = FONTS[key].get('variations', {})
    font.set_variations(variations)
    buffer = hb.Buffer()
    buffer.add_str(text)
    buffer.guess_segment_properties()
    # SVG letter spacing suppresses optional ligatures. These supplied labels
    # have one glyph per character; reject a changed source requiring new rules.
    hb.shape(font, buffer, {'kern': True, 'liga': False, 'clig': False})
    if len(buffer.glyph_infos) != len(text):
        raise ValueError(f'Layout requires review: {text}')
    if any(info.codepoint == 0 for info in buffer.glyph_infos):
        raise ValueError(f'Missing glyph: {text}')
    scale = float(element.attrib['font-size']) / face.upem
    spacing = float(element.get('letter-spacing', '0'))
    advance = sum(p.x_advance * scale + spacing for p in buffer.glyph_positions)
    cursor = float(element.attrib['x'])
    if element.get('text-anchor') == 'middle':
        cursor -= advance / 2
    elif element.get('text-anchor', 'start') != 'start':
        raise ValueError('Unsupported text anchor')
    baseline = float(element.attrib['y'])
    glyphs = tt.getGlyphSet(location=variations or None)
    paths = SVGPathPen(glyphs, ntos=number)
    bounds = BoundsPen(glyphs)
    for info, position in zip(buffer.glyph_infos, buffer.glyph_positions):
        transform = (scale, 0, 0, -scale,
                     cursor + position.x_offset * scale,
                     baseline - position.y_offset * scale)
        glyph = glyphs[tt.getGlyphName(info.codepoint)]
        glyph.draw(TransformPen(paths, transform))
        glyph.draw(TransformPen(bounds, transform))
        cursor += position.x_advance * scale + spacing
    path = ET.Element(f'{{{NS}}}path', {
        'fill': element.attrib['fill'], 'd': paths.getCommands(),
    })
    return path, {
        'text': text, 'font': key, 'advance': float(number(advance)),
        'paintBounds': rounded(bounds.bounds),
    }


def svg_bytes(svg):
    ET.indent(svg, space='  ')
    return (ET.tostring(svg, encoding='unicode') + '\n').encode('utf-8')


def generate(fonts):
    results, layouts = {}, {}
    for orientation in ['horizontal', 'vertical']:
        name = f'lockup-{orientation}.svg'
        source = (SOURCES / name).read_bytes()
        svg = ET.fromstring(source)
        runs = []
        x, y, width, height = map(float, svg.attrib['viewBox'].split())
        for element in list(svg):
            if element.tag != f'{{{NS}}}text':
                continue
            path, run = outline_text(element, fonts)
            left, top, right, bottom = run['paintBounds']
            if not (x <= left <= right <= x + width and
                    y <= top <= bottom <= y + height):
                raise ValueError(f'Original viewBox clips {name}: {run}')
            svg.insert(list(svg).index(element), path)
            svg.remove(element)
            runs.append(run)
            if orientation == 'horizontal':
                label = 'cn' if run['font'] == 'han-heavy' else 'latin'
                standalone = ET.Element(f'{{{NS}}}svg', {
                    'viewBox': ' '.join(number(v) for v in
                                       (left - 2, top - 2, right - left + 4,
                                        bottom - top + 4)),
                    'role': 'img', 'aria-label': run['text'],
                })
                ET.SubElement(standalone, f'{{{NS}}}title').text = run['text']
                standalone.append(copy.deepcopy(path))
                results[f'wordmark-{label}.svg'] = svg_bytes(standalone)
                if label == 'cn':
                    results['brand_wordmark_paths.dart'] = dart_wordmark(
                        path, run['paintBounds'])
        results[name] = svg_bytes(svg)
        layouts[name] = {
            'source': f'tool/generate_wordmark_sources/{name}',
            'sourceSha256': digest(source),
            'viewBox': svg.attrib['viewBox'], 'runs': runs,
        }
    manifest = {
        'schemaVersion': 1,
        'generator': 'tool/generate_wordmark.py',
        'dependencies': DEPENDENCIES,
        'fonts': FONTS,
        'licenses': LICENSES,
        'layouts': layouts,
        'outputs': {str(output_path(name).relative_to(ROOT)):
                    {'sha256': digest(data), 'bytes': len(data)}
                    for name, data in sorted(results.items())},
    }
    results['wordmark-manifest.json'] = (
        json.dumps(manifest, ensure_ascii=False, indent=2) + '\n'
    ).encode('utf-8')
    return results


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--font-dir', type=Path, required=True)
    parser.add_argument('--download', action='store_true')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, version in DEPENDENCIES.items():
        if importlib.metadata.version(name) != version:
            parser.error(f'Install {name}=={version} for reproducible output')
    for filename, info in LICENSES.items():
        if digest((ROOT / filename).read_bytes()) != info['sha256']:
            parser.error(f'License differs from upstream: {filename}')
    results = generate(load_fonts(args.font_dir, args.download))
    for name, data in results.items():
        path = output_path(name)
        if args.check:
            if not path.exists() or path.read_bytes() != data:
                parser.exit(1, f'Wordmark is stale: {name}\n')
        else:
            path.write_bytes(data)
    print('Wordmark outlines, source bounds, font hashes and licenses verified.')


if __name__ == '__main__':
    main()
